server:
  port: 9000
  servlet.context-path: /
  tomcat:
    uri-encoding: UTF-8
    #最大等待队列长度，默认100
    accept-count: 500

spring:
  profiles:
    active: prod
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.template.entity
  global-config:
    db-config:
      logic-delete-value: 0      #逻辑删除判断
      logic-not-delete-value: 1
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback-spring.xml


