server:
  port: 8086
  tomcat.uri-encoding: utf-8
  servlet.context-path: /

spring:
  profiles:
    active: prod
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  mvc:
    favicon:
      enabled: false
  jackson:
    default-property-inclusion: non_empty

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.easicare.device.entity

logging:
  config: classpath:logback-spring.xml


