#生产环境
#开发级别
spring:
  #数据库以及数据源配置
  application:
    name: prod    #指定应用的名称建议使用小写
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: account,orders,stock
      account:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/account?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
        username: root
        password: root
      orders:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/orders?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
        username: root
        password: root
      stock:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/stock?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
        username: root
        password: root
      hikari:
        validation-query: SELECT 1
        time-between-eviction-runs-millis: 18800
    sharding:
      tables:
        account:
          actual-data-nodes: account.account
        orders:
          actual-data-nodes: orders.orders
        stock:
          actual-data-nodes: stock.stock
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/mydb
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 127.0.0.1:9300
#      properties:
#      path:
#        logs: ./elasticsearch/logs
#        data: ./elasticsearch/data
  redis:
    host: 172.16.20.74
    port: 6379
    password:
    timeout: 10000ms
    database: 1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
