#生产环境
#开发级别
spring:
  #数据库以及数据源配置
  application:
    name: prod    #指定应用的名称建议使用小写
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: wpzd21,wpzmedical,news
      wpzd21:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.192:3306/wpzd21?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
      wpzmedical:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.192:3306/wpzmedical??useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
      news:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.192:3306/news?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
      hikari:
        validation-query: SELECT 1
        time-between-eviction-runs-millis: 18800
    sharding:
      tables:
        kaba_user:
          actual-data-nodes: wpzd21.kaba_user
        kaba_medical_operation:
          actual-data-nodes: wpzmedical.kaba_medical_operation
        news:
          actual-data-nodes: news.news
  #data:
    #mongodb:
      #uri: mongodb://localhost:27017/mydb
    #elasticsearch:
      #cluster-name: elasticsearch
      #cluster-nodes: 127.0.0.1:9300
      #properties:
      #path:
        #logs: ./elasticsearch/logs
        #data: ./elasticsearch/data
  redis:
    host: 192.168.1.161
    port: 6378
    password: 123456
    timeout: 10000ms
    database: 1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0